---
branches:
  only:
  - master
notifications:
  email: false
language: ruby
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
- 1.8.7
- 1.9.3
env:
  matrix:
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.1.1
